[general]
num_cores = 10  # Number of CPU cores to be used. Is set to 1 if video mode is "display"
log_level = "debug"  # Possible values: "debug", "info", "warn", "error"
video_mode = "none" # Video modes are not available for no-opencv build. Change to main branch

[dribbling_detection]
outer_threshold = 20 # Minumum number of frames in an event. Mainly to prevent predictions of jumping 2d coords
inner_threshold = 15 # The time a player is within the inner threshold does not count to outer
frame_skip = 5
min_duration = 1.5  # Minimum duration for an action to be classified as dribbling
inner_radius = 2.1 # Percent of screen from ball
outer_radius = 3.2
outer_in_threshold = 5
outer_out_threshold = 5
ignore_person_classes = true
ignore_teams = true

[visualization]
autoplay = false
scale_factor = 0.6 # Scale factor for video and player bounding boxes. Usually best to keep at 1 if downloading
minimap_x = 20
minimap_y = 200
minimap_width = 926 # Recommended resolution: 926x600. Scale based on display, but keep similar ratio
minimap_height = 600
x_min = -52.0
x_max = 52.0
y_min = -34.0
y_max = 34.0

[data]
# data_path = "/home/eirik/Projects/data/SoccerNetGS" # TODO: Implement "test" for test data path
# data_path = "/home/eirik/Projects/data/dribbling-clips/outputs/run_2025-02-26_23-51-01"
data_path = "/home/eirik/Projects/data/dribbling-clips/outputs/run_2025-02-25_01-15-08"
# subsets = ["train", "valid", "test", "challenge"]
subsets = ["interpolated-predictions"]
output_path = "data/output"
huggingface_dataset_url = "https://datasets-server.huggingface.co/first-rows?dataset=SoccerNet%2FSN-GSR-2025&config=default"
