[general]
num_cores = 10  # Number of CPU cores to be used
log_level = "info"  # Possible values: "debug", "info", "warn", "error"
video_mode = "download" # Possible values: "download", "display" (If using SSH display might be slow)

[dribbling_detection]
threshold = 0.7  # Threshold for dribbling detection confidence
frame_skip = 5
min_dribble_duration = 1.5  # Minimum duration for an action to be classified as dribbling

[data]
data_path = "/home/eirik/Projects/data/SoccerNetGS"
# subsets = ["train", "valid", "test", "challenge"]
subsets = ["train"]
output_path = "data/output"
huggingface_dataset_url = "https://datasets-server.huggingface.co/first-rows?dataset=SoccerNet%2FSN-GSR-2025&config=default"
